"""Extract lyrics text and slide-background images from .pptx / .ppt files.

Used by the worship-video maker to reuse text + visuals from an existing
PPT (typically one previously generated by PPT Maker itself). ``.pptx`` is
read directly with python-pptx; legacy ``.ppt`` files are first converted
via LibreOffice headless because python-pptx cannot parse the binary
PowerPoint format.
"""

import logging
import shutil
import subprocess
from pathlib import Path

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE, PP_PLACEHOLDER

from app.config import settings
from app.services.chinese_service import contains_chinese

logger = logging.getLogger(__name__)

# Placeholder types that carry slide "chrome" rather than lyrics content — we
# skip their text when building the slide body. TITLE in particular is often
# used as a per-page header ("S1 齊來稱頌偉大之神 1/2") in legacy worship
# PPT templates, so we must not include it or even treat it as the song title.
_SKIP_PLACEHOLDER_TYPES = {
    PP_PLACEHOLDER.TITLE,
    PP_PLACEHOLDER.CENTER_TITLE,
    PP_PLACEHOLDER.SUBTITLE,
    PP_PLACEHOLDER.HEADER,
    PP_PLACEHOLDER.FOOTER,
    PP_PLACEHOLDER.SLIDE_NUMBER,
    PP_PLACEHOLDER.DATE,
}


def _find_soffice() -> str | None:
    """Locate the LibreOffice ``soffice`` CLI if it's installed anywhere."""
    from_path = shutil.which("soffice") or shutil.which("libreoffice")
    if from_path:
        return from_path
    mac_bundled = "/Applications/LibreOffice.app/Contents/MacOS/soffice"
    if Path(mac_bundled).exists():
        return mac_bundled
    return None


def convert_ppt_to_pptx(ppt_path: Path, work_dir: Path) -> Path:
    """Convert a legacy ``.ppt`` file to ``.pptx`` via LibreOffice headless.

    Raises ``RuntimeError`` with a friendly message when LibreOffice isn't
    installed so the router can surface the exact install step.
    """
    soffice = _find_soffice()
    if soffice is None:
        raise RuntimeError(
            "LibreOffice is required to read legacy .ppt files. "
            "Install with: brew install --cask libreoffice"
        )

    work_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        soffice,
        "--headless",
        "--convert-to",
        "pptx",
        "--outdir",
        str(work_dir),
        str(ppt_path),
    ]
    logger.info("Converting %s via LibreOffice", ppt_path.name)
    result = subprocess.run(
        cmd, capture_output=True, text=True, timeout=180
    )
    if result.returncode != 0:
        tail = (result.stderr or result.stdout)[-800:]
        raise RuntimeError(f"LibreOffice conversion failed:\n{tail}")

    converted = work_dir / f"{ppt_path.stem}.pptx"
    if not converted.exists():
        raise RuntimeError(
            f"LibreOffice reported success but output not found: {converted}"
        )
    return converted


def _iter_shapes_recursive(shapes):
    """Yield every shape in a collection, recursing into GroupShapes.

    python-pptx's ``slide.shapes`` only iterates top-level shapes; text boxes
    nested inside a PowerPoint "Group" (``MSO_SHAPE_TYPE.GROUP``) are invisible
    to a flat iteration. Many commercial PPT templates group lyrics text with
    decorative art, so without recursion we miss every slide that uses a group.
    """
    for shape in shapes:
        yield shape
        if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
            try:
                yield from _iter_shapes_recursive(shape.shapes)
            except AttributeError:
                # Defensive: some shape types report as GROUP but lack .shapes
                pass


def _is_chrome_placeholder(shape) -> bool:
    """True if the shape is a title / header / footer / page-number / date
    placeholder — the kind of slide chrome that repeats per page and should
    not be extracted as lyrics."""
    if not getattr(shape, "is_placeholder", False):
        return False
    try:
        return shape.placeholder_format.type in _SKIP_PLACEHOLDER_TYPES
    except Exception:
        return False


def _slide_text(slide) -> str:
    """Return all visible text from a slide, preserving line breaks.

    Walks the shape tree recursively (handling Group shapes), skips chrome
    placeholders (title / header / footer / page-number / date), and reads
    via ``paragraph.text`` (which python-pptx implements as a join over all
    runs, fields, and inline elements) rather than manually concatenating
    runs — more robust against special inline content.
    """
    lines: list[str] = []
    for shape in _iter_shapes_recursive(slide.shapes):
        if not shape.has_text_frame:
            continue
        if _is_chrome_placeholder(shape):
            continue
        for para in shape.text_frame.paragraphs:
            text = para.text.strip()
            if text:
                lines.append(text)
    return "\n".join(lines)


def _largest_picture_shape(slide):
    """Return the picture shape with the greatest area, or None."""
    best = None
    best_area = 0
    for shape in slide.shapes:
        if shape.shape_type != MSO_SHAPE_TYPE.PICTURE:
            continue
        area = (shape.width or 0) * (shape.height or 0)
        if area > best_area:
            best_area = area
            best = shape
    return best


def extract_pptx(
    pptx_path: Path,
    session_id: str,
    skip_title_slide: bool = True,
) -> dict:
    """Extract lyrics + per-slide background images from a .pptx file.

    When ``skip_title_slide`` is True (default), slide 0 is treated as the
    title slide: its first line becomes ``title``, its second line (if any)
    becomes ``composer``, and its text is *omitted* from ``lyrics``. The
    slide's background image is still extracted so it can be used as the
    title-frame background in the rendered video.

    Returns:
      {
        "title":      "Amazing Grace",      # from slide 0 line 0 (or "")
        "composer":   "John Newton",        # from slide 0 line 1 (or "")
        "lyrics":     "verse 1...\\n\\nverse 2...",
        "language":   "zh-hans" | "en",
        "backgrounds": [
          {"filename": "<session>/<file>", "url": "/static/extracted-bgs/<session>/<file>"},
          ...                                # one per slide that had a picture
        ],
        "slides":     int,                   # total slides in deck
      }
    """
    prs = Presentation(str(pptx_path))

    out_dir = settings.EXTRACTED_BG_DIR / session_id
    out_dir.mkdir(parents=True, exist_ok=True)

    title = ""
    composer = ""
    slide_texts: list[str] = []
    backgrounds: list[dict[str, str]] = []
    has_zh = False

    total_slides = len(prs.slides)
    logger.info(
        "extract_pptx: %s has %d slide(s)", pptx_path.name, total_slides
    )

    # Only treat slide 0 as a dedicated title slide when its (chrome-filtered)
    # content is short enough to plausibly be just title + composer. Legacy
    # worship PPT templates often use a title placeholder as a per-page header,
    # so slide 0 may already be a full lyrics slide — we must not drop it.
    _MAX_TITLE_SLIDE_LINES = 3

    for idx, slide in enumerate(prs.slides):
        text = _slide_text(slide)
        shapes_total = len(slide.shapes)
        non_blank = [ln for ln in text.split("\n") if ln.strip()]
        logger.info(
            "  slide %d: %d shape(s), %d text line(s)",
            idx + 1,
            shapes_total,
            len(non_blank),
        )
        treat_as_title = (
            skip_title_slide
            and idx == 0
            and total_slides > 1
            and 0 < len(non_blank) <= _MAX_TITLE_SLIDE_LINES
        )

        if treat_as_title:
            title = non_blank[0]
            if len(non_blank) > 1:
                composer = non_blank[1]
            if title and contains_chinese(title):
                has_zh = True
        elif text:
            slide_texts.append(text)
            if contains_chinese(text):
                has_zh = True

        pic = _largest_picture_shape(slide)
        if pic is None:
            continue
        try:
            img = pic.image
            ext = (img.ext or "jpg").lower()
            if ext == "jpeg":
                ext = "jpg"
            fname = f"slide_{idx + 1:03d}.{ext}"
            out_path = out_dir / fname
            out_path.write_bytes(img.blob)
            rel = f"{session_id}/{fname}"
            backgrounds.append(
                {"filename": rel, "url": f"/static/extracted-bgs/{rel}"}
            )
        except Exception:
            logger.exception("Failed to extract picture from slide %d", idx + 1)

    return {
        "title": title,
        "composer": composer,
        "lyrics": "\n\n".join(slide_texts),
        "language": "zh-hans" if has_zh else "en",
        "backgrounds": backgrounds,
        "slides": total_slides,
    }
